version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout

      - run:
          name: Grant execute permission to gradlew
          command: chmod +x gradlew

      - run:
          name: Check gradlew permission
          command: ls -l gradlew

      # Unit tests
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/reports/tests
          destination: unit-test-reports

      # Instrumentation tests
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-25;google_apis;x86

      - store_test_results:
          path: app/build/outputs/androidTest-results

      - store_artifacts:
          path: app/build/reports/androidTests
          destination: android-test-reports

      # Release build
      - run:
          name: Assemble release build
          command: ./gradlew assembleRelease

workflows:
  sample:
    jobs:
      - build-and-test
