version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout

      # Grant permission to gradlew
      - run:
          name: Grant execute permission to gradlew
          command: chmod +x gradlew

      # Restore Gradle cache
      - restore_cache:
          keys:
            - gradle-v1-{{ checksum "build.gradle" }}
            - gradle-v1-

      # Download dependencies
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

      # =========================
      # UNIT TESTS
      # =========================
      - android/run-tests:
          test-command: ./gradlew lint testDebug

      # Store unit test results
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest

      - store_artifacts:
          path: app/build/reports/tests
          destination: unit-test-reports

      # =========================
      # BUILD DEBUG APK 
      # =========================
      - run:
          name: Assemble debug APK
          command: ./gradlew assembleDebug

      # Store DEBUG APK (seperti sample)
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: artifact-file

      # =========================
      # INSTRUMENTATION TEST
      # =========================
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-25;google_apis;x86

      - store_test_results:
          path: app/build/outputs/androidTest-results/connected

      - store_artifacts:
          path: app/build/reports/androidTests
          destination: android-test-reports

      # Save Gradle cache
      - save_cache:
          key: gradle-v1-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
            - ~/.android

workflows:
  sample:
    jobs:
      - build-and-test
