version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout

      # ðŸ”¥ FIX UTAMA
      - run:
          name: Grant execute permission to gradlew
          command: chmod +x gradlew

      # Optional (debug)
      - run:
          name: Check gradlew permission
          command: ls -l gradlew

      # Unit tests
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      # Instrumentation tests
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-25;google_apis;x86

      # Release build
      - run:
          name: Assemble release build
          command: ./gradlew assembleRelease

workflows:
  sample:
    jobs:
      - build-and-test
